export const COUPON_CREATE_REQUEST = 'COUPON_CREATE_REQUEST'
export const COUPON_CREATE_SUCCESS = 'COUPON_CREATE_SUCCESS'
export const COUPON_CREATE_FAIL = 'COUPON_CREATE_FAIL'
export const COUPON_CREATE_RESET = 'COUPON_CREATE_RESET'

export const COUPON_LIST_REQUEST = 'COUPON_LIST_REQUEST'
export const COUPON_LIST_SUCCESS = 'COUPON_LIST_SUCCESS'
export const COUPON_LIST_FAIL = 'COUPON_LIST_FAIL'
export const COUPON_LIST_RESET = 'COUPON_LIST_RESET'

export const COUPON_DELETE_REQUEST = 'COUPON_DELETE_REQUEST'
export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS'
export const COUPON_DELETE_FAIL = 'COUPON_DELETE_FAIL'
export const COUPON_DELETE_RESET = 'COUPON_DELETE_RESET'


export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST'
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS'
export const APPLY_COUPON_FAIL = 'APPLY_COUPON_FAIL'
export const APPLY_COUPON_RESET = 'APPLY_COUPON_RESET'

export const CANCEL_COUPON_REQUEST = 'CANCEL_COUPON_REQUEST'
export const CANCEL_COUPON_SUCCESS = 'CANCEL_COUPON_SUCCESS'
export const CANCEL_COUPON_FAIL = 'CANCEL_COUPON_FAIL'
export const CANCEL_COUPON_RESET = 'CANCEL_COUPON_RESET'